#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Monitors

if [[ $(xrandr -q | grep 'DP-3 connected') ]]; then
    xrandr --output DP-1 --primary --mode 1920x1080 --rotate normal --output DP-3 --mode 1920x1080 --rotate normal --right-of DP-1
fi

bspc monitor DP-1 -d I II III IV V
bspc monitor DP-3 -d VI VII VIII IX X

# pgrep bspswallow || bspswallow &

# BSPWM Config

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a lapce state=floating follow=on

############################################
# BSPWM third party stuff

# Environment variables set everywhere
export EDITOR="nvim"
export VISUAL="nvim"
export TERMINAL="alacritty"
export BROWSER="firefox"

# XDG Paths
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share

# remap caps to escape
setxkbmap -option caps:escape
# add German layout, toggle with both Ctrl keys
setxkbmap -layout us,de
setxkbmap -option 'grp:ctrls_toggle'

# Wallpaper
feh --bg-fill --randomize $HOME/Pictures/Wallpapers/*

# Polybar
bash $HOME/.config/polybar/launch.sh

